ISSUE-64 Tracker Kinozal many downloads
idlesign/torrt pull request #85
Opened 2022-11-07 09:41 UTC by a8t3r

https://github.com/idlesign/torrt/issues/64

Сохраняет дату обновления торрента в конфиге, при `walk` сравнивает даты и пропускает скачивание торрента, если даты не изменились. Для ранее добавленных торрентов работает только после фактического обновления - если торрент не обновлен, скачивание будет продолжаться. Чтобы обойти это ограничение - или руками прописать дату обновления в конфиге, или "пересоздать" торрент - `remove_torrent`, `add_torrent`

P.S. На питоне не пишу, поэтому сильно не пинайте)

2022-11-08 09:55 UTC, idlesign commented
Спасибо. Постараюсь поглядеть на этой неделе.

2022-11-11 09:27 UTC, idlesign requested changes

2022-11-11 09:27 UTC, idlesign commented on torrt/base_tracker.py
> +    def get_torrent(self, url: str, last_updated_date: Optional[datetime]) -> Optional[TorrentData]:
* Умолчанием лучше принять `=None`.
* Здесь и в прочих случаях словом `date_` в `last_updated_date` можно пожертвовать — оно не несёт доп. информации.
* Перед `last_updated_date` поставить `*, `, чтобы аргумент всегда передавали с именем.

2022-11-11 09:27 UTC, idlesign commented on torrt/base_tracker.py
> +            self.log_info(f'Skip torrent download from {download_link} due to missing update')
Формулировка кажется неудачной в плане возможной интерпретации `missing update`.

Пожалуй что-то вроде `Skipped as up to date` должно быть понятнее.

И `log_debug` кажется предпочтительным.

2022-11-11 09:27 UTC, idlesign commented on torrt/trackers/kinozal.py
> +        parts = dt_val.split(' в ')
Тут напрашивается `.partition()` вместо `.split()`.

2022-11-11 09:27 UTC, idlesign commented on tests/trackers/test_kinozal.py
> +        f"GET https://kinozal.me/details.php?id=557593 -> 200: {datafix_read('kinozal.html', encoding='windows-1251')}",
Фикстура с данными толстая получилась. Нужно убрать все дублирующиеся и незначащие элементы.

2022-11-11 11:38 UTC, a8t3r commented on torrt/base_tracker.py
> +    def get_torrent(self, url: str, last_updated_date: Optional[datetime]) -> Optional[TorrentData]:
done

2022-11-11 11:39 UTC, a8t3r commented on torrt/base_tracker.py
> +            self.log_info(f'Skip torrent download from {download_link} due to missing update')
done

2022-11-11 11:39 UTC, a8t3r commented on torrt/trackers/kinozal.py
> +        parts = dt_val.split(' в ')
done

2022-11-11 11:40 UTC, a8t3r commented on tests/trackers/test_kinozal.py
> +        f"GET https://kinozal.me/details.php?id=557593 -> 200: {datafix_read('kinozal.html', encoding='windows-1251')}",
вот тут поясни, не понял.
тест делал по образу и подобию с соседними, там действительно есть копипаста

2022-11-11 14:12 UTC, idlesign commented on tests/trackers/test_kinozal.py
> +        f"GET https://kinozal.me/details.php?id=557593 -> 200: {datafix_read('kinozal.html', encoding='windows-1251')}",
html файл толстый получился, смысла его полностью хранить в репозитории вроде нет, поэтому можно урезать.

2022-11-11 14:37 UTC, a8t3r commented on tests/trackers/test_kinozal.py
> +        f"GET https://kinozal.me/details.php?id=557593 -> 200: {datafix_read('kinozal.html', encoding='windows-1251')}",
done

2022-11-14 05:03 UTC, idlesign approved these changes

2022-11-14 05:04 UTC, merged

2022-11-14 05:04 UTC, idlesign commented
Thank you. Merged.